ccflags-y += -I$(srctree)/lib/lwip/ports/freertos/include
ccflags-y += -I$(srctree)/lib/lwip/src/include
ccflags-y += -I$(srctree)/lib
ccflags-y += -I$(srctree)/api/include

obj-$(CONFIG_DEMO_POWERSAVE_DTIM10)	+= main.o
