obj-$(CONFIG_PINCTRL) 		+= pinctrl-core.o
obj-$(CONFIG_PINCTRL_TS8266) 	+= pinctrl-ts8266.o
obj-$(CONFIG_PINCTRL_SCM1010) 	+= pinctrl-scm1010.o
obj-$(CONFIG_PINCTRL_BCM2836) 	+= pinctrl-bcm2836.o
obj-$(CONFIG_PINCTRL_SCM2010) 	+= pinctrl-scm2010.o
