obj-y += common/
obj-$(CONFIG_DEMO_PROTOCOLS_MQTT) += mqtt/
obj-$(CONFIG_DEMO_PROTOCOLS_MQTT_UART) += mqtt_uart/
obj-$(CONFIG_DEMO_PROTOCOLS_HTTP_SERVER) += http_server/
obj-$(CONFIG_DEMO_PROTOCOLS_COAP) += coap/
obj-$(CONFIG_DEMO_PROTOCOLS_HTTP_CLIENT) += http_client/
