obj-$(CONFIG_SERIAL_SCM2020) += serial-scm2020.o
obj-$(CONFIG_SERIAL_PL011) += serial-pl011.o

obj-y += serial-core.o
obj-$(CONFIG_SERIAL_ATCUART) += serial-atcuart.o

obj-$(CONFIG_SERIAL_SANDBOX) += serial-sandbox.o
