/*
 * Copyright 2022-2024 Senscomm Semiconductor Co., Ltd.	All rights reserved.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#undef 	CONFIG_IFCONFIG_WME_FIX_AC
#define CONFIG_IFCONFIG_WME_FIX_AC 1

#undef 	CONFIG_IEEE80211W
#define CONFIG_IEEE80211W 1

#undef 	CONFIG_BEACON_PROTECT
#define CONFIG_BEACON_PROTECT 1

#undef 	CONFIG_SUPPORT_DUAL_VIF
#define CONFIG_SUPPORT_DUAL_VIF 1

#undef 	CONFIG_MAC_TX_TIMEOUT
#define CONFIG_MAC_TX_TIMEOUT 1

#undef 	CONFIG_SUPPORT_MU_EDCA
#define CONFIG_SUPPORT_MU_EDCA 1

#undef 	CONFIG_SUPPORT_MCC
#define CONFIG_SUPPORT_MCC 1

#undef 	CONFIG_SUPPORT_TWT
#define CONFIG_SUPPORT_TWT 1

#undef 	CONFIG_SCM2020_STATS
#define CONFIG_SCM2020_STATS 1

#undef 	CONFIG_SCM2020_CLI_MAC_DM
#define CONFIG_SCM2020_CLI_MAC_DM 1

#undef CONFIG_SUPPORT_DUAL_INSTANCE

#undef CONFIG_IEEE80211_FAST_TX
#define CONFIG_IEEE80211_FAST_TX 1

#undef CONFIG_SUPPORT_AMSDU_TX
#define CONFIG_SUPPORT_AMSDU_TX 1

#undef CONFIG_ACK_ENABLED_MULTI_TID
#define CONFIG_ACK_ENABLED_MULTI_TID 1

#undef CONFIG_IEEE80211_SOFT_WEP
#define CONFIG_IEEE80211_SOFT_WEP 1

#undef CONFIG_NET80211_PS_POLL
#define CONFIG_NET80211_PS_POLL 1
