ccflags-y += -I$(srctree)/hal/drivers/ble
ccflags-y += -I$(srctree)/hal/drivers/ble/priv
ccflags-$(CONFIG_SUPPORT_GCOV_BLE) += -fprofile-arcs -ftest-coverage

obj-$(CONFIG_BLE_NIMBLE_CTRL) += ble-scm2010.o

