ccflags-y += -I$(srctree)/include/FreeRTOS
ccflags-y += -I$(srctree)/include/freebsd
ccflags-y += -I$(srctree)/lib/
ccflags-y += -I$(srctree)/lib/ifconfig
ccflags-y += -I$(srctree)/lib/lwip/ports/freertos/include
ccflags-y += -I$(srctree)/lib/libifconfig
ccflags-y += -I$(srctree)/lib/lwip/src/include

ccflags-y += -I$(srctree)/api/include

obj-y += connect.o
