ccflags-y += -D__WISE__
ccflags-y += -D__PRINTF__
ccflags-y += -fmerge-all-constants

ccflags-y += -I$(srctree)/include/freebsd
ccflags-y += -I$(srctree)/lib
ccflags-y += -I$(src)
ccflags-y += -I$(srctree)/lib/lwip/src/include
ccflags-y += -I$(srctree)/lib/lwip/ports/freertos/include


obj-y += nuttxif.o
