

ifneq ($(CONFIG_BUILD_ROM),y)

obj-$(CONFIG_CLK_SCM2020)   += clk-scm2020.o
obj-$(CONFIG_CLK_TS8266)    += clk-ts8266.o
obj-$(CONFIG_CLK_SCM1010)   += clk-scm1010.o
obj-$(CONFIG_CLK_BCM2836)   += clk-bcm2836.o
obj-$(CONFIG_CLK_AE250_N22) += clk-ae250-n22.o
obj-$(CONFIG_CLK_SCM2010)   += clk-scm2010.o

endif

obj-y += clk-core.o
