ccflags-y += -I$(srctree)/include/FreeRTOS
ccflags-y += -I$(srctree)/include/freebsd
ccflags-y += -I$(srctree)/lib/net/http_parser
ccflags-y += -I$(srctree)/api/include
ccflags-y += -I$(srctree)/lib/lwip/src/include
ccflags-y += -I$(srctree)/lib/lwip/ports/freertos/include
ccflags-y += -I$(srctree)/lib/mbedtls-2.16.2/include
ccflags-y += -I$(srctree)/lib/net/esp-tls
ccflags-y += -I$(srctree)/lib/net/esp-tls/esp-tls-crypto
ccflags-y += -I$(srctree)/lib/net/tcp-transport/include
ccflags-y += -I$(src)/include
ccflags-y += -I$(src)/lib/include
ccflags-y += -I$(src)/asprintf

obj-y += esp_http_client.o
obj-y += lib/http_auth.o
obj-y += lib/http_header.o
obj-y += lib/http_utils.o
