/*
 * Copyright 2021-2024 Senscomm Semiconductor Co., Ltd.	All rights reserved.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
#ifndef __WISE_LINKER_H__
#define __WISE_LINKER_H__

#define DECLARE_SECTION_INFO(s)				   \
extern char __##s##_start[], __##s##_end[], __##s##_lma[]; \
extern unsigned __##s##_size

#define LMA(s) __##s##_lma
#define VMA(s) __##s##_start
#define SSIZE(s) (__##s##_end - __##s##_start)

#ifndef CONFIG_WATCHER
DECLARE_SECTION_INFO(vector);
DECLARE_SECTION_INFO(init);
DECLARE_SECTION_INFO(rram);
DECLARE_SECTION_INFO(text);
DECLARE_SECTION_INFO(rodata);
DECLARE_SECTION_INFO(data);
DECLARE_SECTION_INFO(bss);
#ifdef CONFIG_USE_KERNEL_BSS_DEFAULT_SECTION
DECLARE_SECTION_INFO(kernel);
#endif
#ifdef CONFIG_SUPPORT_NODE_POOL
DECLARE_SECTION_INFO(nodebss);
#endif
#ifdef CONFIG_PM_MULTI_CORE
DECLARE_SECTION_INFO(pmsigram);
#endif
DECLARE_SECTION_INFO(pmrram);
DECLARE_SECTION_INFO(watcher);
DECLARE_SECTION_INFO(waon);
DECLARE_SECTION_INFO(shm1);
DECLARE_SECTION_INFO(shm2);
#ifdef CONFIG_LINK_TO_ROM
DECLARE_SECTION_INFO(romd);
DECLARE_SECTION_INFO(romb);
#endif

#ifdef CONFIG_SUPPORT_GCOV
DECLARE_SECTION_INFO(init_array);
DECLARE_SECTION_INFO(gcovdata);
DECLARE_SECTION_INFO(gcovbss);
#endif
#else
DECLARE_SECTION_INFO(pmrram);
#endif
#endif /* __WISE_LINKER_H__ */
