#ccflags-y += -I$(src) -I$(src)/spiffs/src

obj-$(CONFIG_SPIFFS) += spiffs/

obj-$(CONFIG_CMD_CAT) += cat.o
obj-$(CONFIG_CMD_CP) += cp.o
obj-$(CONFIG_CMD_LS) += ls.o
obj-$(CONFIG_CMD_MV) += mv.o
obj-$(CONFIG_CMD_RM) += rm.o
