ccflags-y += -I$(srctree)/include/FreeRTOS
ccflags-y += -I$(srctree)/include/freebsd
ccflags-y += -I$(srctree)/lib/
ccflags-y += -I$(srctree)/lib/ifconfig
ccflags-y += -I$(srctree)/lib/lwip/ports/freertos/include
ccflags-y += -I$(srctree)/lib/libifconfig
ccflags-y += -I$(srctree)/lib/lwip/src/include

ccflags-y += -I$(srctree)/lib/net/coap/libcoap/include
ccflags-y += -I$(srctree)/lib/net/coap/port/include

ccflags-y += -I$(srctree)/lib/mbedtls-2.28.10/include

ccflags-y += -I$(srctree)/lib/net/esp_http_client/include
ccflags-y += -I$(srctree)/lib/net/esp-tls

ccflags-y += -I$(srctree)/api/include

ccflags-y += -I$(srctree)/api/examples/protocols/common

obj-y += main.o
