/*
 * Copyright 2018-2024 Senscomm Semiconductor Co., Ltd.	All rights reserved.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#ifndef __BITOPS_H__
#define __BITOPS_H__

#ifndef BIT
#define BIT(x)  (0x1UL << (x))
#endif

#define BITAND(A, B) (((uint32_t)A)&((uint32_t)B))
#define BITOR(A, B) (((uint32_t)A)|((uint32_t)B))
#define BITNOT(D) (~D)
#define BITXOR(A, B) (A^B)

#define BITS(D, M) (D = BITOR(D,M))
#define BITC(D, M) (D = BITAND(D,BITNOT(M)))
#define BITSC(D, M, C) (D = BITOR(M,BITAND(D,BITNOT(C))))

#endif
