ccflags-y += -I$(srctree)/include/FreeRTOS
ccflags-y += -I$(srctree)/include/freebsd
ccflags-y += -I$(srctree)/api/include
ccflags-y += -I$(srctree)/lib/
ccflags-y += -I$(srctree)/lib/at
ccflags-y += -I$(srctree)/lib/hostap/wpa_supplicant
ccflags-y += -I$(srctree)/lib/hostap/src/
ccflags-y += -I$(srctree)/lib/hostap/src/utils
ccflags-y += -I$(srctree)/lib/hostap/src/common
ccflags-y += -I$(srctree)/lib/ifconfig
ccflags-y += -I$(srctree)/lib/lwip/ports/freertos/include
ccflags-y += -I$(srctree)/lib/libifconfig
ccflags-y += -I$(srctree)/lib/lwip/src/include
ccflags-y += -I$(srctree)/lib/net/dhcps
ccflags-y += -I$(srctree)/lib/scdc

obj-$(CONFIG_WIFI_API_CLI_DEMO) += cli/main.o
obj-$(CONFIG_WIFI_API_STA_DEMO) += sta/main.o
obj-$(CONFIG_WIFI_API_SOFTAP_DEMO) += softap/main.o

