ccflags-y += -I$(srctree)/api/include

obj-$(CONFIG_DEMO_LEDC_BLINK)      += ledc_blink/main.o
obj-$(CONFIG_DEMO_LEDC_PWM)        += ledc_pwm/main.o
obj-$(CONFIG_DEMO_I2C_EEPROM_SIM)  += i2c_eeprom/main.o i2c_eeprom/eeprom_master.o i2c_eeprom/eeprom_slave.o
obj-$(CONFIG_DEMO_SPI_TRANSFER)    += spi_transfer/main.o spi_transfer/spi_master.o spi_transfer/spi_slave.o
obj-$(CONFIG_DEMO_ADC)             += adc/main.o
obj-$(CONFIG_DEMO_ADC_TEMPERATURE) += adc_temper/temper.o
obj-$(CONFIG_DEMO_TIMER_PWM_IR)    += timer_pwm_ir/timer_pwm_ir.o
