ccflags-y += -I$(srctree)/include/FreeRTOS
ccflags-y += -I$(srctree)/include/freebsd
ccflags-y += -I$(srctree)/lib/
ccflags-y += -I$(srctree)/lib/ifconfig
ccflags-y += -I$(srctree)/lib/lwip/ports/freertos/include
ccflags-y += -I$(srctree)/lib/libifconfig
ccflags-y += -I$(srctree)/lib/lwip/src/include

ccflags-y += -I$(srctree)/lib/net/mqtt/coreMQTT/source/include
ccflags-y += -I$(srctree)/lib/net/mqtt/coreMQTT/source/interface
ccflags-y += -I$(srctree)/lib/tls-transport
ccflags-y += -I$(srctree)/lib/mbedtls-2.16.2/include

ccflags-y += -I$(srctree)/api/include

ccflags-y += -I$(srctree)/api/examples/protocols/common

obj-y += main.o
