ccflags-y += -I$(srctree)/include/freebsd

ccflags-y += -I$(srctree)/lib/net/mqtt/coreMQTT/source/include
ccflags-y += -I$(srctree)/lib/net/mqtt/coreMQTT/source/interface

ccflags-y += -I$(src)/source/include

obj-y += source/core_mqtt_agent.o
obj-y += source/core_mqtt_agent_command_functions.o
