#!/bin/sh

bname_with_ext=$(basename "$1")
bname="${bname_with_ext%.*}"
ext="${bname_with_ext##*.}"
nname=${bname}"_"${ext}
echo "/* Autogenerated with $0 */"
echo "const unsigned char ${nname}[] = {"
od -v -A n -t x1 $1 | sed 's/ *\(..\) */0x\1,/g'
echo "};"
echo "const unsigned int ${nname}_size = sizeof(${nname});"
