/*
 * Copyright 2018-2024 Senscomm Semiconductor Co., Ltd.	All rights reserved.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#ifndef __WISE_FCNTL_H__
#define __WISE_FCNTL_H__

#include_next <fcntl.h>

#ifndef __USE_NATIVE_HEADER__

extern int (*os_fcntl) (int fd, int cmd, ...);

#define fcntl(fd, cmd, ...) os_fcntl(fd, cmd, ##__VA_ARGS__)

#endif /* __USE_NATIVE_HEADER__ */

#endif /* __WISE_FCNTL_H__ */
