#ifndef __VERSION_H__
#define __VERSION_H__

#include <hal/types.h>
#include <timestamp.h>
#include <generated/version_autogenerated.h>

#ifdef __cplusplus
extern "C" {
#endif

#define WISE_VERSION_STRING WISE_VERSION " (" WISE_DATE " - " \
	WISE_TIME " " WISE_TZ ")"

extern const char version_string[];

#if defined(CONFIG_HOSTBOOT) || defined(CONFIG_SUPPORT_SCDC)
/**
 * struct sncmf_rev_info - device revision info.
 *
 * @vendorid: PCI vendor id.
 * @deviceid: device id of chip.
 * @radiorev: radio revision.
 * @chiprev: chip revision.
 * @corerev: core revision.
 * @boardid: board identifier (usu. PCI sub-device id).
 * @boardvendor: board vendor (usu. PCI sub-vendor id).
 * @boardrev: board revision.
 * @driverrev: driver version.
 * @ucoderev: microcode version.
 * @bus: bus type.
 * @chipnum: chip number.
 * @phytype: phy type.
 * @phyrev: phy revision.
 * @anarev: anacore rev.
 * @chippkg: chip package info.
 * @nvramrev: nvram revision number.
 */

struct sncmf_rev_info {
	u32 vendorid;
	u32 deviceid;
	u32 radiorev;
	u32 chiprev;
	u32 corerev;
	u32 boardid;
	u32 boardvendor;
	u32 boardrev;
	u32 driverrev;
	u32 ucoderev;
	u32 bus;
	u32 chipnum;
	u32 phytype;
	u32 phyrev;
	u32 anarev;
	u32 chippkg;
	u32 nvramrev;
};

extern void sncmf_get_revinfo(struct sncmf_rev_info *revinfo);

#endif

#ifdef __cplusplus
}
#endif

#endif
