ccflags-y += -I$(srctree)/include/freebsd
ccflags-y += -I$(srctree)/lib/
ccflags-y += -I$(srctree)/lib/net80211
ccflags-y += -I$(srctree)/lib/lwip/src/include
ccflags-y += -I$(srctree)/lib/lwip/ports/freertos/include

obj-y += dhcps.o

