ccflags-y += -I$(srctree)/include/freebsd

ccflags-y += -I$(src)/source/include
ccflags-y += -I$(src)/source/interface

obj-y += source/core_mqtt.o
obj-y += source/core_mqtt_serializer.o
obj-y += source/core_mqtt_state.o
